### ISSUE TITLE
calling the backend api without validating the input

### ISSUE THREAD

**Issue by Rishi9868** [PriyanshuPatil/quikr-bazaar#61]
https://github.com/PriyanshuPatil/quikr-bazaar/blob/753f49273dca1c74ca8a6f9744ebc2da220ba815/quikr-bazaar-clone/src/Pages/LoginB/InnerB.jsx#L26

**Comment by PriyanshuPatil** [comment]
https://github.com/PriyanshuPatil/Resell.com/blob/main/Resell-Frontend/src/Pages/LoginB/InnerB.jsx 
Resolved:- from line number 28-72 (also handle in backend)
