### ISSUE TITLE
Error is not handle properly

### ISSUE THREAD

**Issue by Rishi9868** [PriyanshuPatil/quikr-bazaar#63]
https://github.com/PriyanshuPatil/quikr-bazaar/blob/753f49273dca1c74ca8a6f9744ebc2da220ba815/quikr-bazaar-clone/src/Pages/LoginB/InnerB.jsx#L30

**Comment by PriyanshuPatil** [comment]
https://github.com/PriyanshuPatil/Resell.com/blob/main/Resell-Frontend/src/Pages/LoginB/InnerB.jsx 
Resolved:- in line number 64 (error handled in backend)
