### ISSUE TITLE
functionality is missing only icon is present

### ISSUE THREAD

**Issue by Rishi9868** [PriyanshuPatil/quikr-bazaar#64]
https://github.com/PriyanshuPatil/quikr-bazaar/blob/753f49273dca1c74ca8a6f9744ebc2da220ba815/quikr-bazaar-clone/src/Pages/LoginB/InnerB.jsx#L181

**Comment by PriyanshuPatil** [comment]
https://github.com/PriyanshuPatil/Resell.com/blob/main/Resell-Frontend/src/Pages/LoginB/InnerB.jsx 
Resolved:- in line number 197 (login with facebook icon is now removed)
