### ISSUE TITLE
sign up page is missing, how new user will access the website 

### ISSUE THREAD

**Issue by Rishi9868** [PriyanshuPatil/quikr-bazaar#65]
https://github.com/PriyanshuPatil/quikr-bazaar/blob/753f49273dca1c74ca8a6f9744ebc2da220ba815/quikr-bazaar-clone/src/Pages/LoginB/InnerB.jsx#L206

**Comment by PriyanshuPatil** [comment]
https://resell1.netlify.app/register 
Resolved:- Now it has been added
