### ISSUE TITLE
Error is not handle properly

### ISSUE THREAD

**Issue by Rishi9868** [PriyanshuPatil/quikr-bazaar#66]
https://github.com/PriyanshuPatil/quikr-bazaar/blob/753f49273dca1c74ca8a6f9744ebc2da220ba815/quikr-bazaar-clone/src/redux/auth/auth.api.js#L8

**Comment by PriyanshuPatil** [comment]
https://github.com/PriyanshuPatil/Resell.com/blob/main/Resell-Frontend/src/redux/auth/auth.actions.js
Resolved:- No error handled in backend and used reducer for that
