### ISSUE TITLE
functionality is not working

### ISSUE THREAD

**Issue by Rishi9868** [PriyanshuPatil/quikr-bazaar#67]
https://github.com/PriyanshuPatil/quikr-bazaar/blob/753f49273dca1c74ca8a6f9744ebc2da220ba815/quikr-bazaar-clone/src/Components/Footer/Footer.jsx#L30

**Comment by PriyanshuPatil** [comment]
https://github.com/PriyanshuPatil/Resell.com/blob/main/Resell-Frontend/src/Components/Footer/Footer.jsx
Resolved:- Now It is Working (Line Number 41)
https://resell1.netlify.app/
