### ISSUE TITLE
page is not responsive

### ISSUE THREAD

**Issue by Rishi9868** [PriyanshuPatil/quikr-bazaar#68]
https://github.com/PriyanshuPatil/quikr-bazaar/blob/753f49273dca1c74ca8a6f9744ebc2da220ba815/quikr-bazaar-clone/src/Components/Footer/Footer.jsx#L40

**Comment by PriyanshuPatil** [comment]
https://github.com/PriyanshuPatil/Resell.com/blob/main/Resell-Frontend/src/Components/Footer/Footer.jsx
Resolved:- Now It is Responsive (Line Number 21-34)
https://resell1.netlify.app/
