### ISSUE TITLE
redirect is not working

### ISSUE THREAD

**Issue by Rishi9868** [PriyanshuPatil/quikr-bazaar#70]
https://github.com/PriyanshuPatil/quikr-bazaar/blob/753f49273dca1c74ca8a6f9744ebc2da220ba815/quikr-bazaar-clone/src/Pages/HomeBB/CarouselB.jsx#L86

**Comment by PriyanshuPatil** [comment]
Resolved:- Now It is Working to ,i have created new page component for that
https://github.com/PriyanshuPatil/Resell.com/blob/main/Resell-Frontend/src/Pages/Home/HomePage.jsx
https://resell1.netlify.app/
