### ISSUE TITLE
input validation is missing

### ISSUE THREAD

**Issue by Rishi9868** [PriyanshuPatil/quikr-bazaar#73]
https://github.com/PriyanshuPatil/quikr-bazaar/blob/753f49273dca1c74ca8a6f9744ebc2da220ba815/quikr-bazaar-clone/src/Components/PostAdForm/PostAdForm.jsx#L71

**Comment by PriyanshuPatil** [comment]
https://github.com/PriyanshuPatil/Resell.com/blob/main/Resell-Frontend/src/Components/PostAdForm/PostAdForm.jsx
Resolved:- From Line (74-96)
